### ISSUE TITLE
Wisconsin 53705 missing

### ISSUE THREAD

**Issue by ldonforth** [jeffkaufman/trycontra#11]
I'm not sure if it's an error in the caller-zips.json file or one of the other steps, but the Madison, WI zip 53705 doesn't seem to propagate to the caller heatmap. 53703, the Madison dance, does; and that's more pertinent. But I thought you'd want to know there's a bug somewhere. 

53705 is the last zip in the list. If it's how I'm passing you the caller zips, let me know and I'll change my protocol.

**Comment by jeffkaufman** [comment]
The problem was that I had forgotten to deploy after merging your pull request.

Fixed!
