### ISSUE TITLE
Consider including end date and dance styles for long events

### ISSUE THREAD

**Issue by qwandor** [jeffkaufman/trycontra#23]
Hello,
It would be useful if the event data in `events.json` included end dates as well as start dates for each event.

Also, are all these events only contra, or do some include other dance styles, or perhaps other dance styles and not contra?

(For context, I run https://folkdance.page/ and am looking for more sources of event data to import; you can see what I currently have at https://github.com/qwandor/dancelist-data/.)

**Comment by jeffkaufman** [comment]
> It would be useful if the event data in events.json included end dates as well as start dates for each event.

Collecting end dates would be possible, but I'm not sure it's worth the additional effort?  Unless you're volunteering? (If you did want to do this, I could give you edit access to the spreadsheet and add a new column for it.)

> are all these events only contra, or do some include other dance styles, or perhaps other dance styles and not contra?

All of them include at least contra, but many include other styles as well, most commonly ECD.

> I run https://folkdance.page/ and am looking for more sources of event data to import

Happy for you or anyone else to pull in my listings!

**Comment by qwandor** [comment]
Sure, if you add a new column I can go through and fill it in for existing events. Do you want to add a column for styles as well?

**Comment by jeffkaufman** [comment]
I've now added this for 2024, and filled it out for all the ones listing dates.  I think it's not worth it going back for 2023 and earlier?

**Comment by qwandor** [comment]
Thanks!

**Comment by qwandor** [comment]
Can you still give me access to the spreadsheet so I can clean up some of the data? You can add my account qwandor@gmail.com.

**Comment by jeffkaufman** [comment]
@qwandor done!  Let me know when you make changes so I can pull them into github
